### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by Aman-Codes** [fnplus/footsteps-flutter-app#14]
**Is your feature request related to a problem? Please describe.**
This repository does not have a CONTRIBUTING.md file and as a GSSOC participant I would like to add it.

**Describe the solution you'd like**
I would like to add CONTRIBUTING.md file to include the following mentioned features
* How to clone the repository
* Adding  reference to the original repository
* Updating local copy of repository
* Creating a new branch
* Pushing commits
* If possible we can also include some pictures in it for a better look 
* It should also include the link to the pull request template, bug report and feature request template
* Update README.md to include the link of CONTRIBUTING.md

**Comment by xlogix** [comment]
@shreyakapoor08

**Comment by shreyakapoor08** [comment]
can I work on this?

**Comment by xlogix** [comment]
Yes, please take clues from the merged contributing file in the previous repo. Emojis would be good!

**Comment by shreyakapoor08** [comment]
@xlogix PR raised. Please let me know if any corrections are required
