### ISSUE TITLE
Add Code_Of_conduct.md file

### ISSUE THREAD

**Issue by csharp489** [fnplus/footsteps-flutter-app#19]
No Code_Of_Conduct.md file is present. 
As a gssoc participant, I would like to add a Code_of_conduct.md file in this project.
@xlogix please assign me this task.

**Comment by xlogix** [comment]
Assigned!

**Comment by sujeetyadav01** [comment]
Is this issue still open

**Comment by xlogix** [comment]
No, it has already been added. Please look into other issues from the project.
