### ISSUE TITLE
To change logo of the app

### ISSUE THREAD

**Issue by Yashank18** [fnplus/footsteps-flutter-app#8]

**Comment by pembemiriam** [comment]
@Yashank18 , @xlogix , I will like to work on this issue

**Comment by Abbeyme1** [comment]
@Yashank18 i can change it if its still not done.

**Comment by Yashank18** [comment]
@Abbeyme1 I will be creating a Pr today. I am already done  with this. 😄

**Comment by Abbeyme1** [comment]
@Yashank18 np man. I was looking something as everything was occupied. :) .
