### ISSUE TITLE
Update Readme of the project

### ISSUE THREAD

**Issue by xlogix** [fnplus/footsteps-flutter-app#9]
Add details about the project goals, timelines & steps to launch/develop the app on the local machine.

**Comment by ghost** [comment]
Will the information be provided? @xlogix

**Comment by xlogix** [comment]
Yes, we can discuss it on Slack.

**Comment by xlogix** [comment]
Anyone working on this?

**Comment by greyhatlinux** [comment]
well @xlogix I can document this 
provided i get the resources :smile:

**Comment by xlogix** [comment]
Ping me on Slack!

**Comment by Sapna2001** [comment]
Can I work on this?

**Comment by xlogix** [comment]
Please contact me or Praveen on Slack for details.

**Comment by Kuljeet-123** [comment]
@xlogix Can I work on this issue??

**Comment by xlogix** [comment]
Assigned!

**Comment by Kuljeet-123** [comment]
@xlogix Please review my PR and Let me know if I have to do some correction.

**Comment by sujeetyadav01** [comment]
Can i work on this issue??

**Comment by xlogix** [comment]
This issue is no longer available. Please take up other issues.
